### ISSUE TITLE
Build guide

### ISSUE THREAD

**Issue by brneor** [Cipulot/CorneECRevival#2]
Sorry for bothering you with this but are you willing to provide a build guide?

Thank you very much for your work on this board, really apreciate it :)

**Comment by Cipulot** [comment]
Hi there 👋 
I'm in the process of creating a build guide rn, with a dedicated section at the end about the calibration process too.
It will be available here and on the dedicated Notion page linked in the home of the repo. Here's a quick [link](https://cipulot.notion.site/Corne-EC-Revival-203d1983000b400290df213aa76ce73b) for reference. I think that by the end of the week I'll have it finished.

**Comment by brneor** [comment]
Thank you so much! I've already read your Notion pages and although I'm a electronic illiterate I appreciate your effort in creating such detailed documentation :)

**Comment by Cipulot** [comment]
Hi there @brneor 👋 ,
I've added the build guide to the [Notion page](https://cipulot.notion.site/Corne-EC-Revival-203d1983000b400290df213aa76ce73b), detailing the PCB building and parts, as well as the mechanical assembly(standoffs, screws and case).
