### ISSUE TITLE
what is the manufacturer and specific model of Q_NMOS_GSD？

### ISSUE THREAD

**Issue by zhushenzhi** [Cipulot/CorneECRevival#4]
Hello, I'm replicating a keyboard and having trouble sourcing the right Q_NMOS_GSD component. The JLC recommendations seem incorrect due to package model inconsistencies. Could you advise on the correct manufacturer, model, voltage, and current for Q_NMOS_GSD?

**Comment by Cipulot** [comment]
`Q1` and `R8` can be left unpopulated.
